name: Microfrontend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "packages/container/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]  # Adjust as necessary

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Debug Output
        run: |
          echo "Node.js version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Current directory contents:"
          ls -l

      - name: Install dependencies
        run: npm install
        working-directory: packages/container

      - name: Build microfrontend
        run: npm run build
        working-directory: packages/container

      # Add deployment steps here if needed
